## Wrie a Simple Program for Tutorial 2

## Section A

 A) Write a tensorflow program that pass two 1-D array of same size. The passed arrays must be have element-wise multiplication. The final result is also multiplied by constant. The program must display its output?

### Step 1 : Load the Tensorflow and Create session

In [22]:
import tensorflow as tf
sess=tf.Session()
import numpy as np

### Step 2: Define array variables and placeholders

In [23]:
X_vals=np.array([3.,5.,6.,9.])
y_vals=np.array([3., 7., -1., -2.])
const=tf.constant([5.])
X_plac=tf.placeholder(tf.float32)
y_plac=tf.placeholder(tf.float32)

### Step 3: Define a model for tensorflow work

In [24]:
output=tf.multiply(const, tf.multiply(X_plac, y_plac))

### Step 4: Generate Output

In [25]:
for i in range (4):
    print(sess.run(output, feed_dict={X_plac:X_vals[i], y_plac:y_vals[i]}))

[45.]
[175.]
[-30.]
[-90.]


## Section B

B) Write a tensorflow program that pass two 1-D array of same size. The passed arrays should have vector wise multiplication and provide the results. The program must display its output?

### Step 1 : Load TensorFlow and start a session

In [26]:
import tensorflow as tf
import numpy as np 
sess=tf.Session()


### Step 2 :  Define input vectors and placeholders

In [75]:
# The input matrix consists input vectors as 
X_vals=np.array([[1., 5., -2,], [3., 4., 8.], [-1., 3., -4]])
y_vals=np.array([[3., 6., 7.], [2.,3.,6.], [1., 4., 7.]])

# we are performing between vectors: 
X_plac=tf.placeholder(shape=(3), dtype=tf.float32)
y_plac=tf.placeholder(shape=(3),  dtype=tf.float32)

### Step 3: Define a model with tensorflow

In [76]:
output=tf.multiply(X_plac, y_plac)
# they are just a 1-D vector input in each time, we can directly multiply them.

### Step 4: Display the results

In [78]:
 for i in range (3):
        X_input=X_vals[i,:]
        y_input=y_vals[:, i]
        print(sess.run(output, feed_dict={X_plac:X_input, y_plac:y_input}))

[ 3. 10. -2.]
[18. 12. 32.]
[ -7.  18. -28.]


## Section C:

B) Write a tensorflow program that pass two 2-D array of same size. The passed arrays should have vector wise multiplication and provide the results.The program must display its output?

#### Section B can be used for 2-Vectors as well as 

In [79]:
# The input matrix consists input vectors as 
X_vals=np.array([[1., 5., -2,], [3., 4., 8.], [-1., 3., -4]])
y_vals=np.array([[3., 6., 7.], [2.,3.,6.], [1., 4., 7.]])

# we are performing between vectors: 
X_plac=tf.placeholder(shape=(3, 1), dtype=tf.float32)
y_plac=tf.placeholder(shape=(1, 3),  dtype=tf.float32)

In [80]:
output=tf.matmul(X_plac, y_plac)

In [81]:
 for i in range (3):
        X_input=X_vals[i,:]
        X_input=np.reshape(X_input, (3, 1))
        y_input=y_vals[i, :]
        y_input=np.reshape(y_input, (1, 3))
        print(sess.run(output, feed_dict={X_plac:X_input, y_plac:y_input}))

[[  3.   6.   7.]
 [ 15.  30.  35.]
 [ -6. -12. -14.]]
[[ 6.  9. 18.]
 [ 8. 12. 24.]
 [16. 24. 48.]]
[[ -1.  -4.  -7.]
 [  3.  12.  21.]
 [ -4. -16. -28.]]


#### Note: you need to study about matrix reshaping, matrix multiplication and placeholder definition for further study. 