# Simple program for Tutorial 1

In [2]:
#A) Load the tensorflow and session 
import tensorflow as tf
import numpy as np
sess=tf.Session()


### A) Element-wise Addition of Two matrix 

In [6]:
# A) Addition of Two matrix
A=tf.convert_to_tensor(np.array([[1., 4., 6.],[3., 2., 1.]]))
B= tf.convert_to_tensor(np.array([[-3., 2., 0.], [6., 1., 3.]]))    
print (sess.run(A+B))

[[-2.  6.  6.]
 [ 9.  3.  4.]]


### B) Inverse of a Matrix: used tf.matrix_inverse function.


Meaning of inverse transformation: If we have matrix X that produce matrix Y, then there should be some sort of transformation. That Transformation can be defined by matrix A. But it we know Y and we need to find X, then we have to undo the Transformation A. The undo transformation of A is known as inverse of A.  $A{-1} $ itself is a transformation.  

In [9]:
# B) Inverse of a matrix 
C=tf.convert_to_tensor(np.array([[2., 4., 3.], [1., 3., 7.], [3., 5., 6.]]))
print(sess.run(tf.matrix_inverse(C)))

[[-1.21428571 -0.64285714  1.35714286]
 [ 1.07142857  0.21428571 -0.78571429]
 [-0.28571429  0.14285714  0.14285714]]


If matrix is symmetric positive definite then matrix inverse method follows cholesky 
decomposition otherwise it use LU decomposition. 
For cholesky decomposition  use= tf.cholesky(C)

### C) Calculate Eigen values and Eigen Vectors

Eigen values simply gives how much a vector in that direction is strecteched. since Eigen vectors are orthogonal 
with eigen the values, they that measured just a strectch of vectors orthgonally in their corresponding axis. 


In [12]:
D=tf.convert_to_tensor(np.array([[1., 4., 3.], [3.,4.,2.],[2., 2., 1.]]))
print(sess.run(tf.self_adjoint_eig(D)))

(array([-1.22123701,  0.11523239,  7.10600462]), array([[ 0.82624389,  0.24545232,  0.50702485],
       [-0.2896801 , -0.58680799,  0.75613611],
       [-0.4831216 ,  0.77162785,  0.41374386]]))


The eigen values are in first rows. 
And subsequent vectors are the eign values. This can be known as eigen decomposition of a matrix.

[[[1. 2. 3. 4.]
  [2. 3. 4. 5.]
  [3. 4. 5. 6.]]

 [[2. 3. 4. 5.]
  [3. 4. 5. 6.]
  [4. 5. 6. 7.]]]
[[100.]
 [130.]
 [160.]]
[[130.]
 [160.]
 [190.]]
